namespace AuroraAudioStudio.Services;

public sealed class LocalizationService(SettingsService settings)
{
    private readonly Dictionary<string, string[]> values = new(StringComparer.OrdinalIgnoreCase)
    {
        ["home"] = ["首页", "首頁", "Home", "ホーム"],
        ["homeSubtitle"] = ["选择一个功能，直接开始当前任务。", "選擇一個功能，直接開始目前任務。", "Choose a feature and start your task.", "機能を選んで、すぐにタスクを始めましょう。"],
        ["tasks"] = ["任务中心", "任務中心", "Task Center", "タスクセンター"],
        ["tasksSubtitle"] = ["查看排队、处理中、已完成与可恢复的任务。", "查看排隊、處理中、已完成與可恢復的任務。", "Review queued, running, completed, and recoverable tasks.", "待機中、処理中、完了、復旧可能なタスクを確認します。"],
        ["results"] = ["成品库", "成品庫", "Results", "成果ライブラリ"],
        ["resultsSubtitle"] = ["集中查看本地生成的音轨、MIDI、字幕与其他成品。", "集中查看本機產生的音軌、MIDI、字幕與其他成品。", "Browse locally generated stems, MIDI, subtitles, and other results.", "ローカルで生成したステム、MIDI、字幕などをまとめて確認します。"],
        ["music"] = ["音乐创作", "音樂創作", "Music", "音楽制作"],
        ["voice"] = ["AI配音与声音克隆", "AI配音與聲音複製", "AI Voice", "AI音声"],
        ["singing"] = ["歌声克隆", "歌聲複製", "Singing Voice", "歌声変換"],
        ["separation"] = ["去人声 / AI分轨", "去人聲 / AI分軌", "Stem Separation", "音源分離"],
        ["transcription"] = ["AI扒谱（MIDI）", "AI扒譜（MIDI）", "AI Transcription", "AI採譜（MIDI）"],
        ["subtitles"] = ["视频 AI 字幕", "影片 AI 字幕", "Video Subtitles", "動画 AI 字幕"],
        ["settings"] = ["设置", "設定", "Settings", "設定"],
        ["about"] = ["关于", "關於", "About", "このアプリについて"],
        ["release"] = ["结束当前引擎", "結束目前引擎", "Stop current engine", "現在のエンジンを終了"],
        ["output"] = ["我的成品", "我的成品", "My creations", "マイ作品"],
        ["update"] = ["检查更新", "檢查更新", "Check updates", "更新を確認"],
        ["releaseNotesTitle"] = ["版本更新日志", "版本更新記錄", "Release notes", "更新履歴"],
        ["currentVersion"] = ["当前版本", "目前版本", "Current", "現在"],
        ["close"] = ["关闭", "關閉", "Close", "閉じる"],
        ["workbenchLabel"] = ["本地 AI 音频创作工作台", "本機 AI 音訊創作工作台", "Local AI audio production workbench", "ローカル AI オーディオ制作ワークベンチ"],
        ["models"] = ["模型中心", "模型中心", "Model Center", "モデルセンター"],
        ["maintenance"] = ["维护与恢复", "維護與復原", "Maintenance", "メンテナンス"],
        ["maintenanceSubtitle"] = ["检查环境、恢复任务并导出可用于排障的诊断信息。", "檢查環境、恢復任務並匯出可用於除錯的診斷資訊。", "Check the environment, recover tasks, and export diagnostics.", "環境を確認し、タスクを復旧して診断情報を出力します。"],
        ["settingsSubtitle"] = ["按你的习惯调整 Aurora。", "依照你的習慣調整 Aurora。", "Adapt Aurora to the way you work.", "作業スタイルに合わせて Aurora を調整します。"],
        ["aboutSubtitle"] = ["认识 Aurora，查看新变化。", "認識 Aurora，查看最新變更。", "Learn about Aurora and review what's new.", "Aurora の情報と新機能を確認します。"],
        ["modelsSubtitle"] = ["了解每款创作引擎，并管理安装、版本与更新。", "瞭解每款創作引擎，並管理安裝、版本與更新。", "Understand each engine and manage installs, versions, and updates.", "各エンジンを確認し、インストール、バージョン、更新を管理します。"],
        ["diagnostics"] = ["导出诊断", "匯出診斷", "Diagnostics", "診断を出力"],
        ["website"] = ["GitHub", "GitHub", "GitHub", "GitHub"],
        ["back"] = ["返回工作台", "返回工作台", "Back to studio", "スタジオに戻る"],
        ["ready"] = ["本地创作", "本機創作", "Local creation", "ローカル制作"],
        ["updateChecking"] = ["正在连接 GitHub…", "正在連線至 GitHub…", "Connecting to GitHub…", "GitHub に接続しています…"],
        ["updateAlreadyRunning"] = ["更新检查或安装正在进行，请稍候。", "更新檢查或安裝正在進行，請稍候。", "An update check or installation is already in progress.", "更新の確認またはインストールが進行中です。"],
        ["updateDownloading"] = ["正在下载 Aurora {0}", "正在下載 Aurora {0}", "Downloading Aurora {0}", "Aurora {0} をダウンロード中"],
        ["updateVerifying"] = ["正在验证安装包完整性", "正在驗證安裝程式完整性", "Verifying installer integrity", "インストーラーを検証中"],
        ["updatePreparingInstall"] = ["正在启动安全安装程序", "正在啟動安全安裝程式", "Starting the verified installer", "検証済みインストーラーを起動中"],
        ["updateInstallerHandoff"] = ["下载与校验已完成。即将交给系统安装界面，完成后会自动打开新版。", "下載與驗證已完成。即將交由系統安裝介面，完成後會自動開啟新版。", "Download and verification are complete. Windows Setup will take over and reopen the new version when finished.", "ダウンロードと検証が完了しました。Windows のインストール画面に切り替わり、完了後に新バージョンを自動起動します。"],
        ["updateUpToDate"] = ["当前已是最新版本。", "目前已是最新版本。", "Aurora Audio Studio is up to date.", "現在のバージョンは最新です。"],
        ["updateReady"] = ["已找到经过校验的正式更新。", "已找到經過驗證的正式更新。", "A verified update is ready to install.", "検証済みの正式アップデートをインストールできます。"],
        ["updateAssetsIncomplete"] = ["发现新版本，但安装包或校验文件尚未完整发布。", "發現新版本，但安裝程式或驗證檔案尚未完整發布。", "A new version exists, but its verified update assets are incomplete.", "新しいバージョンがありますが、検証用ファイルが揃っていません。"],
        ["updateCheckFailed"] = ["检查更新失败：{0}", "檢查更新失敗：{0}", "Update check failed: {0}", "更新の確認に失敗しました：{0}"],
        ["updateUnavailable"] = ["当前没有可校验的更新安装包。", "目前沒有可驗證的更新安裝程式。", "No verifiable update package is available.", "検証可能な更新パッケージがありません。"],
        ["updateChecksumInvalid"] = ["更新校验文件无效，已停止安装。", "更新驗證檔案無效，已停止安裝。", "The update checksum file is invalid. Installation was stopped.", "更新チェックサムが無効なため、インストールを中止しました。"],
        ["updateVerificationFailed"] = ["安装包校验失败，已删除下载文件。", "安裝程式驗證失敗，已刪除下載檔案。", "Update verification failed. The downloaded installer was removed.", "インストーラーの検証に失敗したため、ダウンロードを削除しました。"],
        ["updateStarted"] = ["安全安装程序已启动。请批准 Windows 权限提示；安装完成后 Aurora 会自动重新打开。", "安全安裝程式已啟動。請允許 Windows 權限提示；安裝完成後 Aurora 會自動重新開啟。", "The verified installer has started. Approve the Windows prompt; Aurora will reopen automatically after installation.", "検証済みインストーラーを起動しました。Windows の確認後、完了すると Aurora が自動的に再起動します。"],
        ["updateInstallFailed"] = ["更新安装失败：{0}", "更新安裝失敗：{0}", "Update installation failed: {0}", "更新のインストールに失敗しました：{0}"],
        ["updateFound"] = ["发现 {0}：{1}", "發現 {0}：{1}", "Version {0}: {1}", "バージョン {0}：{1}"],
        ["updateDialogTitle"] = ["Aurora Audio Studio 更新", "Aurora Audio Studio 更新", "Aurora Audio Studio update", "Aurora Audio Studio アップデート"],
        ["updateDialogBody"] = ["当前版本 {0}，最新版本 {1}。Aurora 将从 GitHub 下载并校验安装包，然后自动覆盖安装。", "目前版本 {0}，最新版本 {1}。Aurora 將從 GitHub 下載並驗證安裝程式，然後自動覆蓋安裝。", "Installed: {0}. Latest: {1}. Aurora will download and verify the installer from GitHub, then install it over the current version.", "現在のバージョンは {0}、最新は {1} です。GitHub からインストーラーを取得して検証し、現在のバージョンを更新します。"],
        ["updateInstall"] = ["下载并安装", "下載並安裝", "Download and install", "ダウンロードしてインストール"],
        ["later"] = ["稍后", "稍後", "Later", "後で"],
        ["openWorkbench"] = ["进入工作台", "進入工作台", "Open workbench", "ワークベンチを開く"],
        ["installModel"] = ["自动安装模型", "自動安裝模型", "Install model", "モデルを自動インストール"],
        ["modelReady"] = ["已安装 · 可使用", "已安裝 · 可使用", "Installed · Ready", "インストール済み · 利用可能"],
        ["modelMissing"] = ["尚未安装", "尚未安裝", "Not installed", "未インストール"],
        ["modelInstallTitle"] = ["安装创作模型", "安裝創作模型", "Install creative model", "制作モデルをインストール"],
        ["modelInstallLocation"] = ["安装位置", "安裝位置", "Install location", "インストール先"],
        ["modelDownloadSize"] = ["预计下载", "預計下載", "Estimated download", "推定ダウンロード"],
        ["modelFreeSpace"] = ["建议预留空间", "建議預留空間", "Recommended free space", "推奨空き容量"],
        ["modelRootNotice"] = ["更改位置会同时更新 Aurora 的模型目录；现有模型不会移动。", "變更位置會同時更新 Aurora 的模型目錄；現有模型不會移動。", "Changing this location also changes Aurora's model folder. Existing models will not be moved.", "場所を変更すると Aurora のモデルフォルダーも変更されます。既存モデルは移動しません。"],
        ["installHere"] = ["安装到此位置", "安裝到此位置", "Install here", "ここにインストール"],
        ["changeModelFolder"] = ["更改模型目录…", "變更模型目錄…", "Change model folder…", "モデルフォルダーを変更…"],
        ["modelInstalling"] = ["正在安装 {0}…", "正在安裝 {0}…", "Installing {0}…", "{0} をインストール中…"],
        ["modelInstallIncomplete"] = ["安装流程已结束，但未检测到完整模型文件。请在模型中心检查或修复。", "安裝流程已結束，但未偵測到完整模型檔案。請在模型中心檢查或修復。", "Installation finished, but the complete model was not detected. Check or repair it in Model Center.", "インストールは終了しましたが、完全なモデルを確認できません。モデルセンターで確認または修復してください。"],
        ["diagnosticsPreviewTitle"] = ["导出诊断前确认", "匯出診斷前確認", "Review diagnostics export", "診断出力の確認"],
        ["diagnosticsPreviewBody"] = ["将导出 {0} 个本地日志文件。Aurora 会先隐藏 Windows 用户目录、用户名、模型目录、成品目录和处理记录目录；文件只保存到你的成品目录，不会自动上传。", "將匯出 {0} 個本機日誌檔案。Aurora 會先隱藏 Windows 使用者目錄、使用者名稱、模型目錄、成品目錄與處理記錄目錄；檔案只會儲存到成品目錄，不會自動上傳。", "Aurora will export {0} local log files after redacting the Windows profile, user name, model folder, output folder, and processing-record folder. The archive is saved locally and is never uploaded automatically.", "{0} 個のローカルログを出力します。Windows ユーザーフォルダー、ユーザー名、モデル、出力、処理履歴のパスは伏せ字にされ、ファイルが自動送信されることはありません。"],
        ["diagnosticsExportRedacted"] = ["脱敏后导出", "遮蔽後匯出", "Export redacted archive", "伏せ字で出力"],
        ["diagnosticsExported"] = ["诊断包已脱敏导出。", "診斷套件已遮蔽個人路徑並匯出。", "The redacted diagnostics archive was exported.", "個人パスを伏せた診断ファイルを出力しました。"],
        ["taskWaiting"] = ["等待中", "等待中", "Waiting", "待機中"],
        ["taskPreparing"] = ["准备中", "準備中", "Preparing", "準備中"],
        ["taskRunning"] = ["处理中", "處理中", "Running", "処理中"],
        ["taskCompleted"] = ["已完成", "已完成", "Completed", "完了"],
        ["taskFailed"] = ["未完成", "未完成", "Failed", "未完了"],
        ["taskCanceled"] = ["已取消", "已取消", "Canceled", "キャンセル済み"],
        ["taskInterrupted"] = ["可恢复", "可復原", "Recoverable", "復旧可能"],
        ["activeTaskCount"] = ["{0} 个任务正在等待或处理", "{0} 個任務正在等待或處理", "{0} tasks are waiting or running", "{0} 件のタスクが待機中または処理中です"],
        ["navigationName"] = ["Aurora 主导航", "Aurora 主導覽", "Aurora main navigation", "Aurora メインナビゲーション"],
        ["workbenchLoadingAutomation"] = ["正在启动本地创作引擎", "正在啟動本機創作引擎", "Starting the local creative engine", "ローカル制作エンジンを起動中"],
        ["workbenchAutomation"] = ["本地 AI 创作工作台", "本機 AI 創作工作台", "Local AI creative workbench", "ローカル AI 制作ワークベンチ"],
        ["updateProgressAutomation"] = ["下载与安装进度", "下載與安裝進度", "Download and installation progress", "ダウンロードとインストールの進捗"],
        ["healthEngines"] = ["创作引擎", "創作引擎", "Creative engines", "制作エンジン"],
        ["healthModelStorage"] = ["模型存储", "模型儲存空間", "Model storage", "モデル保存先"],
        ["healthOutputStorage"] = ["成品存储", "成品儲存空間", "Output storage", "出力保存先"],
        ["healthTaskRecovery"] = ["任务恢复", "任務復原", "Task recovery", "タスク復旧"],
        ["healthRecords"] = ["处理记录", "處理記錄", "Processing records", "処理履歴"],
        ["healthSafeMode"] = ["安全模式", "安全模式", "Safe mode", "セーフモード"],
        ["healthGood"] = ["良好", "良好", "Good", "良好"],
        ["healthCheck"] = ["需要检查", "需要檢查", "Check required", "確認が必要"],
        ["healthUnavailable"] = ["不可用", "無法使用", "Unavailable", "利用不可"],
        ["healthCreate"] = ["需要创建", "需要建立", "Create required", "作成が必要"],
        ["healthEnabled"] = ["已启用", "已啟用", "Enabled", "有効"],
        ["healthDisabled"] = ["未启用", "未啟用", "Disabled", "無効"],
        ["healthRecover"] = ["需要恢复", "需要復原", "Recovery required", "復旧が必要"],
        ["healthComponents"] = ["{0}/{1} 个组件可用", "{0}/{1} 個元件可用", "{0}/{1} components available", "{0}/{1} コンポーネントが利用可能"],
        ["healthDiskAvailable"] = ["{0} · 可用 {1:0.0} GB", "{0} · 可用 {1:0.0} GB", "{0} · {1:0.0} GB available", "{0} · 空き {1:0.0} GB"],
        ["healthTaskRecoveryDetail"] = ["异常退出后保留任务、处理记录与诊断记录", "異常結束後保留任務、處理記錄與診斷記錄", "Tasks, processing records, and diagnostics survive an unexpected exit", "異常終了後もタスク、処理履歴、診断記録を保持"],
        ["healthRecordsGood"] = ["未发现损坏或不兼容的处理记录", "未發現損壞或不相容的處理記錄", "No damaged or incompatible processing records found", "破損または非対応の処理履歴はありません"],
        ["healthRecordsRecover"] = ["{0} 个记录已保留恢复副本", "{0} 個記錄已保留復原副本", "Recovery copies retained for {0} records", "{0} 件の復旧コピーを保持しています"],
        ["healthSafeOn"] = ["第三方创作引擎不会自动启动", "第三方創作引擎不會自動啟動", "Third-party creative engines will not start automatically", "外部制作エンジンは自動起動しません"],
        ["healthSafeOff"] = ["所有已安装引擎均可启动", "所有已安裝引擎均可啟動", "All installed engines may start", "インストール済みエンジンを起動できます"],
    };

    private readonly Dictionary<string, string[]> phrases = new(StringComparer.OrdinalIgnoreCase)
    {
        ["分轨模式"] = ["分轨模式", "分軌模式", "Stem mode", "ステムモード"],
        ["二轨：人声 + 伴奏"] = ["二轨：人声 + 伴奏", "二軌：人聲 + 伴奏", "Two stems: vocals + instrumental", "2 ステム：ボーカル + 伴奏"],
        ["多轨：完整分轨"] = ["多轨：完整分轨", "多軌：完整分軌", "Multi-stem: full separation", "マルチステム：完全分離"],
        ["今天想创作什么？"] = ["今天想创作什么？", "今天想創作什麼？", "What would you like to create?", "今日は何を作りますか？"],
        ["六个功能互相独立，不需要先新建项目。选择功能后，再按提示添加素材、模型和输出位置。"] = ["六个功能互相独立，不需要先新建项目。选择功能后，再按提示添加素材、模型和输出位置。", "六個功能彼此獨立，不需要先建立專案。選擇功能後，再依提示加入素材、模型和輸出位置。", "All six features work independently—no project setup required. Choose a feature, then follow the prompts for media, models, and output location.", "6つの機能はそれぞれ独立しており、プロジェクト作成は不要です。機能を選び、素材、モデル、出力先の案内に従ってください。"],
        ["创作音乐"] = ["创作音乐", "創作音樂", "Create music", "音楽を作る"],
        ["制作配音"] = ["制作配音", "製作配音", "Create a voice", "音声を作る"],
        ["克隆歌声"] = ["克隆歌声", "克隆歌聲", "Clone singing voice", "歌声をクローン"],
        ["转换与克隆演唱音色"] = ["转换与克隆演唱音色", "轉換與克隆演唱音色", "Convert and clone singing voices", "歌声の変換とクローン"],
        ["拆分混音"] = ["拆分混音", "拆分混音", "Split a mix", "ミックスを分離"],
        ["音频转 MIDI"] = ["音频转 MIDI", "音訊轉 MIDI", "Audio to MIDI", "音声を MIDI へ"],
        ["生成字幕"] = ["生成字幕", "產生字幕", "Generate subtitles", "字幕を生成"],
        ["第一次使用？直接选择功能"] = ["第一次使用？直接选择功能", "第一次使用？直接選擇功能", "New here? Choose a feature", "初めてですか？機能を選びましょう"],
        ["不需要新建项目。进入任一功能后，Aurora 会根据当前任务提示所需的素材、模型和输出位置。"] = ["不需要新建项目。进入任一功能后，Aurora 会根据当前任务提示所需的素材、模型和输出位置。", "不需要建立專案。進入任一功能後，Aurora 會依目前任務提示所需的素材、模型和輸出位置。", "No project setup is required. Open any feature and Aurora will prompt for the media, model, and output location needed for that task.", "プロジェクト作成は不要です。機能を開くと、タスクに必要な素材、モデル、出力先が案内されます。"],
        ["最近处理记录"] = ["最近处理记录", "最近處理記錄", "Recent processing records", "最近の処理履歴"],
        ["再次处理"] = ["再次处理", "再次處理", "Run again", "再処理"],
        ["完成分轨、扒谱或字幕任务后，处理记录会出现在这里。"] = ["完成分轨、扒谱或字幕任务后，处理记录会出现在这里。", "完成分軌、扒譜或字幕任務後，處理記錄會顯示在這裡。", "Processing records appear here after separation, transcription, or subtitle tasks finish.", "分離、採譜、字幕タスクの完了後、処理履歴がここに表示されます。"],
        ["正在进行"] = ["正在进行", "進行中", "In progress", "進行中"],
        ["查看全部任务"] = ["查看全部任务", "查看全部任務", "View all tasks", "すべてのタスク"],
        ["所有本地任务"] = ["所有本地任务", "所有本機任務", "All local tasks", "すべてのローカルタスク"],
        ["继续"] = ["继续", "繼續", "Continue", "続ける"],
        ["打开"] = ["打开", "開啟", "Open", "開く"],
        ["重试"] = ["重试", "重試", "Retry", "再試行"],
        ["取消"] = ["取消", "取消", "Cancel", "キャンセル"],
        ["检查全部更新"] = ["检查全部更新", "檢查全部更新", "Check all updates", "すべて更新確認"],
        ["更新全部"] = ["更新全部", "全部更新", "Update all", "すべて更新"],
        ["有更新"] = ["有更新", "有更新", "Update available", "更新あり"],
        ["更新"] = ["更新", "更新", "Update", "更新"],
        ["安装"] = ["安装", "安裝", "Install", "インストール"],
        ["稍后"] = ["稍后", "稍後", "Later", "後で"],
        ["将按顺序更新所有已发现的新版本，并保留可回退版本。是否继续？"] = ["将按顺序更新所有已发现的新版本，并保留可回退版本。是否继续？", "將依序更新所有已發現的新版本，並保留可回復版本。是否繼續？", "Aurora will update every detected component in sequence and keep rollback copies. Continue?", "検出したすべてのコンポーネントを順番に更新し、ロールバック用のコピーを保持します。続行しますか？"],
        ["组件正在使用"] = ["组件正在使用", "元件正在使用", "Component in use", "コンポーネントを使用中"],
        ["请先保存并关闭 {0}，然后重新点击更新。Aurora 不会强制关闭它，以免丢失未保存内容。"] = ["请先保存并关闭 {0}，然后重新点击更新。Aurora 不会强制关闭它，以免丢失未保存内容。", "請先儲存並關閉 {0}，再重新點擊更新。Aurora 不會強制關閉它，以免遺失未儲存內容。", "Save your work and close {0}, then select Update again. Aurora will not force-close it, so unsaved work is protected.", "作業を保存して {0} を終了し、もう一度更新してください。未保存の内容を守るため、Aurora は強制終了しません。"],
        ["以下组件仍在运行，请先保存并关闭后再更新：\n{0}"] = ["以下组件仍在运行，请先保存并关闭后再更新：\n{0}", "以下元件仍在執行中，請先儲存並關閉後再更新：\n{0}", "These components are still running. Save your work and close them before updating:\n{0}", "次のコンポーネントが実行中です。作業を保存して終了してから更新してください：\n{0}"],
        ["知道了"] = ["知道了", "知道了", "Got it", "了解"],
        ["查看本地文件"] = ["查看本地文件", "查看本機檔案", "View local files", "ローカルファイル"],
        ["检查 / 修复"] = ["检查 / 修复", "檢查 / 修復", "Check / Repair", "確認 / 修復"],
        ["回退"] = ["回退", "回復", "Roll back", "ロールバック"],
        ["卸载"] = ["卸载", "解除安裝", "Uninstall", "アンインストール"],
        ["重新扫描"] = ["重新扫描", "重新掃描", "Scan again", "再スキャン"],
        ["导出诊断包"] = ["导出诊断包", "匯出診斷套件", "Export diagnostics", "診断を出力"],
        ["打开日志"] = ["打开日志", "開啟日誌", "Open logs", "ログを開く"],
        ["运行环境"] = ["运行环境", "執行環境", "Runtime environment", "実行環境"],
        ["安全模式"] = ["安全模式", "安全模式", "Safe mode", "セーフモード"],
        ["任务完成后释放显存"] = ["任务完成后释放显存", "任務完成後釋放顯示記憶體", "Release VRAM after tasks", "完了後に VRAM を解放"],
        ["外观与语言"] = ["外观与语言", "外觀與語言", "Appearance and language", "表示と言語"],
        ["界面语言"] = ["界面语言", "介面語言", "Interface language", "表示言語"],
        ["主题"] = ["主题", "主題", "Theme", "テーマ"],
        ["模型目录"] = ["模型目录", "模型目錄", "Model folder", "モデルフォルダー"],
        ["成品目录"] = ["成品目录", "成品目錄", "Output folder", "出力フォルダー"],
        ["处理记录目录"] = ["处理记录目录", "處理記錄目錄", "Processing records folder", "処理履歴フォルダー"],
        ["保存设置"] = ["保存设置", "儲存設定", "Save settings", "設定を保存"],
        ["每天首次启动时检查应用更新"] = ["每天首次启动时检查应用更新", "每天首次啟動時檢查應用程式更新", "Check app updates on the first launch each day", "毎日の初回起動時にアプリ更新を確認"],
        ["启动时检查模型更新"] = ["启动时检查模型更新", "啟動時檢查模型更新", "Check model updates at startup", "起動時にモデル更新を確認"],
        ["下载大型模型前始终确认"] = ["下载大型模型前始终确认", "下載大型模型前一律確認", "Confirm large model downloads", "大容量モデルの前に確認"],
        ["任务完成后自动释放显存"] = ["任务完成后自动释放显存", "任務完成後自動釋放顯示記憶體", "Release VRAM automatically", "VRAM を自動解放"],
        ["进入工作台"] = ["进入工作台", "進入工作台", "Open workbench", "ワークベンチを開く"],
        ["查看我的成品"] = ["查看我的成品", "查看我的成品", "View my creations", "作品を見る"],
        ["开始处理"] = ["开始处理", "開始處理", "Start processing", "処理を開始"],
        ["选择文件"] = ["选择文件", "選擇檔案", "Choose file", "ファイルを選択"],
        ["打开成品目录"] = ["打开成品目录", "開啟成品目錄", "Open output folder", "出力フォルダー"],
        ["检查更新"] = ["检查更新", "檢查更新", "Check for updates", "更新を確認"],
        ["导出诊断"] = ["导出诊断", "匯出診斷", "Export diagnostics", "診断を出力"],
        ["我的成品"] = ["我的成品", "我的成品", "My creations", "マイ作品"],
        ["结束当前引擎"] = ["结束当前引擎", "結束目前引擎", "Stop current engine", "現在のエンジンを終了"],
        ["创作引擎与模型"] = ["创作引擎与模型", "創作引擎與模型", "Creative engines and models", "制作エンジンとモデル"],
        ["正在读取本地模型…"] = ["正在读取本地模型…", "正在讀取本機模型…", "Reading local models…", "ローカルモデルを確認しています…"],
        ["全部模型"] = ["全部模型", "全部模型", "All models", "すべてのモデル"],
        ["已安装"] = ["已安装", "已安裝", "Installed", "インストール済み"],
        ["默认组件"] = ["默认组件", "預設元件", "Default components", "標準コンポーネント"],
        ["可选模型"] = ["可选模型", "選用模型", "Optional models", "オプションモデル"],
        ["0.9.8 · 完整汉化更新提示，扩展模型中心信息，并新增三档 Faster-Whisper 多语言字幕模型。"] = [
            "0.9.8 · 完整汉化更新提示，扩展模型中心信息，并新增三档 Faster-Whisper 多语言字幕模型。",
            "0.9.8 · 完整在地化更新提示、擴充模型中心資訊，並新增三種 Faster-Whisper 多語言字幕模型。",
            "0.9.8 · Localized update results, richer Model Center details, and three additional multilingual Faster-Whisper models.",
            "0.9.8 · 更新結果の完全なローカライズ、モデルセンターの情報拡充、3 種類の多言語 Faster-Whisper モデルを追加。"],
        ["0.9.8 · 本地 AI 音频创作工作台"] = ["0.9.8 · 本地 AI 音频创作工作台", "0.9.8 · 本機 AI 音訊創作工作台", "0.9.8 · Local AI audio production workbench", "0.9.8 · ローカル AI オーディオ制作ワークベンチ"],
        ["为音乐、声音与影像创作者打造的一站式本地工作台。灵感、素材与成品，始终由你掌控。"] = ["为音乐、声音与影像创作者打造的一站式本地工作台。灵感、素材与成品，始终由你掌控。", "為音樂、聲音與影像創作者打造的一站式本機工作台。靈感、素材與成品，始終由你掌控。", "A unified local workbench for music, voice, and video creators. Your ideas, source files, and finished work remain under your control.", "音楽・音声・映像クリエイターのための統合ローカルワークベンチ。アイデア、素材、完成作品は常に自分で管理できます。"],
        ["更新日志"] = ["更新日志", "更新記錄", "Release notes", "更新履歴"],
        ["Copyright © 2026 Aurora Contributors. Licensed under GNU GPL v3.0."] = ["版权所有 © 2026 Aurora Contributors。采用 GNU GPL v3.0 许可。", "版權所有 © 2026 Aurora Contributors。採用 GNU GPL v3.0 授權。", "Copyright © 2026 Aurora Contributors. Licensed under GNU GPL v3.0.", "Copyright © 2026 Aurora Contributors。GNU GPL v3.0 に基づき提供。"],
        ["0.9.7 · 模型选择更完整：新增轻量配音、声音克隆、通用分轨与轻量扒谱引擎，均由用户按需安装。"] = [
            "0.9.7 · 模型选择更完整：新增轻量配音、声音克隆、通用分轨与轻量扒谱引擎，均由用户按需安装。",
            "0.9.7 · 模型選擇更完整：新增輕量配音、聲音複製、通用分軌與輕量扒譜引擎，均由使用者按需安裝。",
            "0.9.7 · More model choices: lightweight speech, voice cloning, general-purpose stems, and MIDI engines are now available on demand.",
            "0.9.7 · モデル選択を拡充：軽量音声、ボイスクローン、汎用音源分離、MIDI エンジンを必要に応じて導入できます。"],
        ["等待本地引擎"] = ["等待本地引擎", "等待本機引擎", "Waiting for local engine", "ローカルエンジンを待機中"],
        ["队列已暂停"] = ["队列已暂停", "佇列已暫停", "Queue paused", "キュー一時停止中"],
        ["正在准备模型与工作区"] = ["正在准备模型与工作区", "正在準備模型與工作區", "Preparing model and workspace", "モデルと作業領域を準備中"],
        ["正在本机处理"] = ["正在本机处理", "正在本機處理", "Processing locally", "ローカルで処理中"],
        ["处理完成"] = ["处理完成", "處理完成", "Processing complete", "処理完了"],
        ["需要处理"] = ["需要处理", "需要處理", "Needs attention", "確認が必要"],
        ["已安全取消"] = ["已安全取消", "已安全取消", "Canceled safely", "安全にキャンセル済み"],
        ["任务已取消。"] = ["任务已取消。", "任務已取消。", "The task was canceled.", "タスクをキャンセルしました。"],
        ["Recovered after restart"] = ["重启后可恢复", "重新啟動後可復原", "Recoverable after restart", "再起動後に復旧可能"],
        ["Aurora closed before this task finished. You can retry it."] = ["Aurora 在任务完成前关闭，可以重新运行此任务。", "Aurora 在任務完成前關閉，可以重新執行此任務。", "Aurora closed before this task finished. You can retry it.", "タスク完了前に Aurora が終了しました。再実行できます。"],
        ["当前没有排队任务"] = ["当前没有排队任务", "目前沒有排隊任務", "No tasks are queued", "待機中のタスクはありません"],
        ["暂停队列"] = ["暂停队列", "暫停佇列", "Pause queue", "キューを一時停止"],
        ["继续队列"] = ["继续队列", "繼續佇列", "Resume queue", "キューを再開"],
        ["等待"] = ["等待", "等待", "Waiting", "待機中"]
    };

    public string Get(string key)
    {
        if (!values.TryGetValue(key, out var options)) return key;
        return settings.EffectiveLanguage() switch
        {
            "zh-TW" => options[1],
            "en-US" => options[2],
            "ja-JP" => options[3],
            _ => options[0]
        };
    }

    public string Translate(string source)
    {
        var pair = phrases.FirstOrDefault(x => x.Value.Contains(source, StringComparer.OrdinalIgnoreCase));
        if (pair.Value is null) return source;
        return settings.EffectiveLanguage() switch { "zh-TW" => pair.Value[1], "en-US" => pair.Value[2], "ja-JP" => pair.Value[3], _ => pair.Value[0] };
    }

    public string Format(string key, params object[] args) => string.Format(Get(key), args);
}
