namespace AuroraAudioStudio.Services;

public sealed class LocalizationService(SettingsService settings)
{
    private readonly Dictionary<string, string[]> values = new(StringComparer.OrdinalIgnoreCase)
    {
        ["home"] = ["首页", "首頁", "Home", "ホーム"],
        ["languageImmediateHint"] = ["选择语言后立即生效并保存，无需点击下方的保存按钮。", "選擇語言後立即生效並儲存，無需點擊下方的儲存按鈕。", "Language changes apply and save immediately; no Save button is needed.", "言語を選ぶとすぐに反映・保存されます。下の保存ボタンを押す必要はありません。"],
        ["languageChanged"] = ["已切换为简体中文。", "已切換為繁體中文。", "Switched to English.", "日本語に切り替えました。"],
        ["sourcesAdded"] = ["已添加 {0} 个素材，等待开始处理", "已加入 {0} 個素材，等待開始處理", "{0} files added, ready to process", "{0} 件の素材を追加しました。処理を開始できます。"],
        ["processSources"] = ["处理 {0} 个素材", "處理 {0} 個素材", "Process {0} files", "{0} 件を処理"],
        ["percentCompleted"] = ["已完成 {0}%", "已完成 {0}%", "{0}% complete", "{0}% 完了"],
        ["batchSubmitted"] = ["已提交 {0} 个任务，将按顺序处理。", "已提交 {0} 個任務，將依序處理。", "Queued {0} tasks for sequential processing.", "{0} 件のタスクを順番に処理します。"],
        ["batchProcessing"] = ["正在处理 {0} / {1}：{2}", "正在處理 {0} / {1}：{2}", "Processing {0} / {1}: {2}", "処理中 {0} / {1}：{2}"],
        ["batchItemCompleted"] = ["已完成：{0}", "已完成：{0}", "Completed: {0}", "完了：{0}"],
        ["batchItemFailed"] = ["未完成：{0}", "未完成：{0}", "Not completed: {0}", "未完了：{0}"],
        ["batchSummary"] = ["已完成 {0} / {1}", "已完成 {0} / {1}", "Completed {0} / {1}", "完了 {0} / {1}"],
        ["resultImportFailed"] = ["收录成品失败：{0}", "收錄成品失敗：{0}", "Could not import results: {0}", "成果を取り込めませんでした：{0}"],
        ["artifactExported"] = ["已导出：{0}", "已匯出：{0}", "Exported: {0}", "書き出しました：{0}"],
        ["midiPreviewHint"] = ["MIDI 包含 {0} 个音符。请用默认音乐软件试听或编辑；Aurora 尚不提供内置 MIDI 合成器。", "MIDI 包含 {0} 個音符。請用預設音樂軟體試聽或編輯；Aurora 尚未提供內建 MIDI 合成器。", "MIDI contains {0} notes. Open it in your music app to listen or edit; Aurora does not include a MIDI synthesizer.", "MIDI に {0} 個のノートがあります。音楽ソフトで試聴・編集してください。Aurora には MIDI 音源は含まれません。"],
        ["homeSubtitle"] = ["选择一个功能，直接开始当前任务。", "選擇一個功能，直接開始目前任務。", "Choose a feature and start your task.", "機能を選んで、すぐにタスクを始めましょう。"],
        ["tasks"] = ["任务中心", "任務中心", "Task Center", "タスクセンター"],
        ["tasksSubtitle"] = ["查看排队、处理中、已完成与可恢复的任务。", "查看排隊、處理中、已完成與可恢復的任務。", "Review queued, running, completed, and recoverable tasks.", "待機中、処理中、完了、復旧可能なタスクを確認します。"],
        ["results"] = ["成品库", "成品庫", "Results", "成果ライブラリ"],
        ["resultsSubtitle"] = ["集中查看本地生成的音轨、MIDI、字幕与其他成品。", "集中查看本機產生的音軌、MIDI、字幕與其他成品。", "Browse locally generated stems, MIDI, subtitles, and other results.", "ローカルで生成したステム、MIDI、字幕などをまとめて確認します。"],
        ["music"] = ["音乐创作", "音樂創作", "Music", "音楽制作"],
        ["voice"] = ["AI配音与声音克隆", "AI配音與聲音複製", "AI Voice", "AI音声"],
        ["singing"] = ["歌声克隆", "歌聲複製", "Singing Voice", "歌声変換"],
        ["separation"] = ["去人声 / AI分轨", "去人聲 / AI分軌", "Stem Separation", "音源分離"],
        ["transcription"] = ["AI扒谱（MIDI）", "AI扒譜（MIDI）", "AI Transcription", "AI採譜（MIDI）"],
        ["subtitles"] = ["视频 AI 字幕", "影片 AI 字幕", "Video Subtitles", "動画 AI 字幕"],
        ["settings"] = ["设置", "設定", "Settings", "設定"],
        ["about"] = ["关于", "關於", "About", "このアプリについて"],
        ["release"] = ["结束当前引擎", "結束目前引擎", "Stop current engine", "現在のエンジンを終了"],
        ["output"] = ["我的成品", "我的成品", "My creations", "マイ作品"],
        ["update"] = ["检查更新", "檢查更新", "Check updates", "更新を確認"],
        ["releaseNotesTitle"] = ["版本更新日志", "版本更新記錄", "Release notes", "更新履歴"],
        ["currentVersion"] = ["当前版本", "目前版本", "Current", "現在"],
        ["close"] = ["关闭", "關閉", "Close", "閉じる"],
        ["workbenchLabel"] = ["本地 AI 音频创作工作台", "本機 AI 音訊創作工作台", "Local AI audio production workbench", "ローカル AI オーディオ制作ワークベンチ"],
        ["models"] = ["模型中心", "模型中心", "Model Center", "モデルセンター"],
        ["maintenance"] = ["维护与恢复", "維護與復原", "Maintenance", "メンテナンス"],
        ["maintenanceSubtitle"] = ["检查环境、恢复任务并导出可用于排障的诊断信息。", "檢查環境、恢復任務並匯出可用於除錯的診斷資訊。", "Check the environment, recover tasks, and export diagnostics.", "環境を確認し、タスクを復旧して診断情報を出力します。"],
        ["settingsSubtitle"] = ["按你的习惯调整 Aurora。", "依照你的習慣調整 Aurora。", "Adapt Aurora to the way you work.", "作業スタイルに合わせて Aurora を調整します。"],
        ["aboutSubtitle"] = ["认识 Aurora，查看新变化。", "認識 Aurora，查看最新變更。", "Learn about Aurora and review what's new.", "Aurora の情報と新機能を確認します。"],
        ["modelsSubtitle"] = ["了解每款创作引擎，并管理安装、版本与更新。", "瞭解每款創作引擎，並管理安裝、版本與更新。", "Understand each engine and manage installs, versions, and updates.", "各エンジンを確認し、インストール、バージョン、更新を管理します。"],
        ["diagnostics"] = ["导出诊断", "匯出診斷", "Diagnostics", "診断を出力"],
        ["website"] = ["GitHub", "GitHub", "GitHub", "GitHub"],
        ["back"] = ["返回工作台", "返回工作台", "Back to studio", "スタジオに戻る"],
        ["ready"] = ["本地创作", "本機創作", "Local creation", "ローカル制作"],
        ["updateChecking"] = ["正在连接 GitHub…", "正在連線至 GitHub…", "Connecting to GitHub…", "GitHub に接続しています…"],
        ["updateAlreadyRunning"] = ["更新检查或安装正在进行，请稍候。", "更新檢查或安裝正在進行，請稍候。", "An update check or installation is already in progress.", "更新の確認またはインストールが進行中です。"],
        ["updateDownloading"] = ["正在下载 Aurora {0}", "正在下載 Aurora {0}", "Downloading Aurora {0}", "Aurora {0} をダウンロード中"],
        ["updateVerifying"] = ["正在验证安装包完整性", "正在驗證安裝程式完整性", "Verifying installer integrity", "インストーラーを検証中"],
        ["updatePreparingInstall"] = ["正在启动安全安装程序", "正在啟動安全安裝程式", "Starting the verified installer", "検証済みインストーラーを起動中"],
        ["updateInstallerHandoff"] = ["下载与校验已完成。即将交给系统安装界面，完成后会自动打开新版。", "下載與驗證已完成。即將交由系統安裝介面，完成後會自動開啟新版。", "Download and verification are complete. Windows Setup will take over and reopen the new version when finished.", "ダウンロードと検証が完了しました。Windows のインストール画面に切り替わり、完了後に新バージョンを自動起動します。"],
        ["updateUpToDate"] = ["当前已是最新版本。", "目前已是最新版本。", "Aurora Audio Studio is up to date.", "現在のバージョンは最新です。"],
        ["updateReady"] = ["已找到经过校验的正式更新。", "已找到經過驗證的正式更新。", "A verified update is ready to install.", "検証済みの正式アップデートをインストールできます。"],
        ["updateAssetsIncomplete"] = ["发现新版本，但安装包或校验文件尚未完整发布。", "發現新版本，但安裝程式或驗證檔案尚未完整發布。", "A new version exists, but its verified update assets are incomplete.", "新しいバージョンがありますが、検証用ファイルが揃っていません。"],
        ["updateCheckFailed"] = ["检查更新失败：{0}", "檢查更新失敗：{0}", "Update check failed: {0}", "更新の確認に失敗しました：{0}"],
        ["updateUnavailable"] = ["当前没有可校验的更新安装包。", "目前沒有可驗證的更新安裝程式。", "No verifiable update package is available.", "検証可能な更新パッケージがありません。"],
        ["updateChecksumInvalid"] = ["更新校验文件无效，已停止安装。", "更新驗證檔案無效，已停止安裝。", "The update checksum file is invalid. Installation was stopped.", "更新チェックサムが無効なため、インストールを中止しました。"],
        ["updateVerificationFailed"] = ["安装包校验失败，已删除下载文件。", "安裝程式驗證失敗，已刪除下載檔案。", "Update verification failed. The downloaded installer was removed.", "インストーラーの検証に失敗したため、ダウンロードを削除しました。"],
        ["updateStarted"] = ["安全安装程序已启动。请批准 Windows 权限提示；安装完成后 Aurora 会自动重新打开。", "安全安裝程式已啟動。請允許 Windows 權限提示；安裝完成後 Aurora 會自動重新開啟。", "The verified installer has started. Approve the Windows prompt; Aurora will reopen automatically after installation.", "検証済みインストーラーを起動しました。Windows の確認後、完了すると Aurora が自動的に再起動します。"],
        ["updateInstallFailed"] = ["更新安装失败：{0}", "更新安裝失敗：{0}", "Update installation failed: {0}", "更新のインストールに失敗しました：{0}"],
        ["updateFound"] = ["发现 {0}：{1}", "發現 {0}：{1}", "Version {0}: {1}", "バージョン {0}：{1}"],
        ["updateDialogTitle"] = ["Aurora Audio Studio 更新", "Aurora Audio Studio 更新", "Aurora Audio Studio update", "Aurora Audio Studio アップデート"],
        ["updateDialogBody"] = ["当前版本 {0}，最新版本 {1}。Aurora 将从 GitHub 下载并校验安装包，然后自动覆盖安装。", "目前版本 {0}，最新版本 {1}。Aurora 將從 GitHub 下載並驗證安裝程式，然後自動覆蓋安裝。", "Installed: {0}. Latest: {1}. Aurora will download and verify the installer from GitHub, then install it over the current version.", "現在のバージョンは {0}、最新は {1} です。GitHub からインストーラーを取得して検証し、現在のバージョンを更新します。"],
        ["updateInstall"] = ["下载并安装", "下載並安裝", "Download and install", "ダウンロードしてインストール"],
        ["later"] = ["稍后", "稍後", "Later", "後で"],
        ["openWorkbench"] = ["进入工作台", "進入工作台", "Open workbench", "ワークベンチを開く"],
        ["installModel"] = ["自动安装模型", "自動安裝模型", "Install model", "モデルを自動インストール"],
        ["modelReady"] = ["已安装 · 可使用", "已安裝 · 可使用", "Installed · Ready", "インストール済み · 利用可能"],
        ["modelMissing"] = ["尚未安装", "尚未安裝", "Not installed", "未インストール"],
        ["modelInstallTitle"] = ["安装创作模型", "安裝創作模型", "Install creative model", "制作モデルをインストール"],
        ["modelInstallLocation"] = ["安装位置", "安裝位置", "Install location", "インストール先"],
        ["modelDownloadSize"] = ["预计下载", "預計下載", "Estimated download", "推定ダウンロード"],
        ["modelFreeSpace"] = ["建议预留空间", "建議預留空間", "Recommended free space", "推奨空き容量"],
        ["modelRootNotice"] = ["更改位置会同时更新 Aurora 的模型目录；现有模型不会移动。", "變更位置會同時更新 Aurora 的模型目錄；現有模型不會移動。", "Changing this location also changes Aurora's model folder. Existing models will not be moved.", "場所を変更すると Aurora のモデルフォルダーも変更されます。既存モデルは移動しません。"],
        ["installHere"] = ["安装到此位置", "安裝到此位置", "Install here", "ここにインストール"],
        ["changeModelFolder"] = ["更改模型目录…", "變更模型目錄…", "Change model folder…", "モデルフォルダーを変更…"],
        ["modelInstalling"] = ["正在安装 {0}…", "正在安裝 {0}…", "Installing {0}…", "{0} をインストール中…"],
        ["modelInstallIncomplete"] = ["安装流程已结束，但未检测到完整模型文件。请在模型中心检查或修复。", "安裝流程已結束，但未偵測到完整模型檔案。請在模型中心檢查或修復。", "Installation finished, but the complete model was not detected. Check or repair it in Model Center.", "インストールは終了しましたが、完全なモデルを確認できません。モデルセンターで確認または修復してください。"],
        ["diagnosticsPreviewTitle"] = ["导出诊断前确认", "匯出診斷前確認", "Review diagnostics export", "診断出力の確認"],
        ["diagnosticsPreviewBody"] = ["将导出 {0} 个本地日志文件。Aurora 会先隐藏 Windows 用户目录、用户名、模型目录、成品目录和处理记录目录；文件只保存到你的成品目录，不会自动上传。", "將匯出 {0} 個本機日誌檔案。Aurora 會先隱藏 Windows 使用者目錄、使用者名稱、模型目錄、成品目錄與處理記錄目錄；檔案只會儲存到成品目錄，不會自動上傳。", "Aurora will export {0} local log files after redacting the Windows profile, user name, model folder, output folder, and processing-record folder. The archive is saved locally and is never uploaded automatically.", "{0} 個のローカルログを出力します。Windows ユーザーフォルダー、ユーザー名、モデル、出力、処理履歴のパスは伏せ字にされ、ファイルが自動送信されることはありません。"],
        ["diagnosticsExportRedacted"] = ["脱敏后导出", "遮蔽後匯出", "Export redacted archive", "伏せ字で出力"],
        ["diagnosticsExported"] = ["诊断包已脱敏导出。", "診斷套件已遮蔽個人路徑並匯出。", "The redacted diagnostics archive was exported.", "個人パスを伏せた診断ファイルを出力しました。"],
        ["taskWaiting"] = ["等待中", "等待中", "Waiting", "待機中"],
        ["taskPreparing"] = ["准备中", "準備中", "Preparing", "準備中"],
        ["taskRunning"] = ["处理中", "處理中", "Running", "処理中"],
        ["taskCompleted"] = ["已完成", "已完成", "Completed", "完了"],
        ["taskFailed"] = ["未完成", "未完成", "Failed", "未完了"],
        ["taskCanceled"] = ["已取消", "已取消", "Canceled", "キャンセル済み"],
        ["taskInterrupted"] = ["可恢复", "可復原", "Recoverable", "復旧可能"],
        ["activeTaskCount"] = ["{0} 个任务正在等待或处理", "{0} 個任務正在等待或處理", "{0} tasks are waiting or running", "{0} 件のタスクが待機中または処理中です"],
        ["navigationName"] = ["Aurora 主导航", "Aurora 主導覽", "Aurora main navigation", "Aurora メインナビゲーション"],
        ["workbenchLoadingAutomation"] = ["正在启动本地创作引擎", "正在啟動本機創作引擎", "Starting the local creative engine", "ローカル制作エンジンを起動中"],
        ["workbenchAutomation"] = ["本地 AI 创作工作台", "本機 AI 創作工作台", "Local AI creative workbench", "ローカル AI 制作ワークベンチ"],
        ["updateProgressAutomation"] = ["下载与安装进度", "下載與安裝進度", "Download and installation progress", "ダウンロードとインストールの進捗"],
        ["healthEngines"] = ["创作引擎", "創作引擎", "Creative engines", "制作エンジン"],
        ["healthModelStorage"] = ["模型存储", "模型儲存空間", "Model storage", "モデル保存先"],
        ["healthOutputStorage"] = ["成品存储", "成品儲存空間", "Output storage", "出力保存先"],
        ["healthTaskRecovery"] = ["任务恢复", "任務復原", "Task recovery", "タスク復旧"],
        ["healthRecords"] = ["处理记录", "處理記錄", "Processing records", "処理履歴"],
        ["healthSafeMode"] = ["安全模式", "安全模式", "Safe mode", "セーフモード"],
        ["healthGood"] = ["良好", "良好", "Good", "良好"],
        ["healthCheck"] = ["需要检查", "需要檢查", "Check required", "確認が必要"],
        ["healthUnavailable"] = ["不可用", "無法使用", "Unavailable", "利用不可"],
        ["healthCreate"] = ["需要创建", "需要建立", "Create required", "作成が必要"],
        ["healthEnabled"] = ["已启用", "已啟用", "Enabled", "有効"],
        ["healthDisabled"] = ["未启用", "未啟用", "Disabled", "無効"],
        ["healthRecover"] = ["需要恢复", "需要復原", "Recovery required", "復旧が必要"],
        ["healthComponents"] = ["{0}/{1} 个组件可用", "{0}/{1} 個元件可用", "{0}/{1} components available", "{0}/{1} コンポーネントが利用可能"],
        ["healthDiskAvailable"] = ["{0} · 可用 {1:0.0} GB", "{0} · 可用 {1:0.0} GB", "{0} · {1:0.0} GB available", "{0} · 空き {1:0.0} GB"],
        ["healthTaskRecoveryDetail"] = ["异常退出后保留任务、处理记录与诊断记录", "異常結束後保留任務、處理記錄與診斷記錄", "Tasks, processing records, and diagnostics survive an unexpected exit", "異常終了後もタスク、処理履歴、診断記録を保持"],
        ["healthRecordsGood"] = ["未发现损坏或不兼容的处理记录", "未發現損壞或不相容的處理記錄", "No damaged or incompatible processing records found", "破損または非対応の処理履歴はありません"],
        ["healthRecordsRecover"] = ["{0} 个记录已保留恢复副本", "{0} 個記錄已保留復原副本", "Recovery copies retained for {0} records", "{0} 件の復旧コピーを保持しています"],
        ["healthSafeOn"] = ["第三方创作引擎不会自动启动", "第三方創作引擎不會自動啟動", "Third-party creative engines will not start automatically", "外部制作エンジンは自動起動しません"],
        ["healthSafeOff"] = ["仅通过完整性检查的引擎可以启动", "僅通過完整性檢查的引擎可以啟動", "Only engines that pass integrity checks can start", "整合性チェックに合格したエンジンのみ起動できます"],
    };

    private readonly Dictionary<string, string[]> phrases = new(StringComparer.OrdinalIgnoreCase)
    {
        ["AI 配音"] = ["AI 配音", "AI 配音", "AI voice", "AI 音声"],
        ["模型包"] = ["模型包", "模型套件", "model package", "モデルパッケージ"],
        ["ACE-Step 隔离运行环境"] = ["ACE-Step 隔离运行环境", "ACE-Step 獨立執行環境", "isolated ACE-Step runtime", "ACE-Step 専用ランタイム"],
        ["ACE-Step 基础权重"] = ["ACE-Step 基础权重", "ACE-Step 基礎權重", "ACE-Step base weights", "ACE-Step 基本モデル"],
        ["ACE-Step 1.5 XL Turbo 官方权重"] = ["ACE-Step 1.5 XL Turbo 官方权重", "ACE-Step 1.5 XL Turbo 官方權重", "official ACE-Step 1.5 XL Turbo weights", "ACE-Step 1.5 XL Turbo 公式モデル"],
        ["Seed-VC Python 3.10 隔离环境"] = ["Seed-VC Python 3.10 隔离环境", "Seed-VC Python 3.10 獨立環境", "isolated Seed-VC Python 3.10 environment", "Seed-VC 専用 Python 3.10 環境"],
        ["Seed-VC 官方权重与配置"] = ["Seed-VC 官方权重与配置", "Seed-VC 官方權重與設定", "official Seed-VC weights and configuration", "Seed-VC 公式モデルと設定"],
        ["Seed-VC CAMPPlus 声纹模型"] = ["Seed-VC CAMPPlus 声纹模型", "Seed-VC CAMPPlus 聲紋模型", "Seed-VC CAMPPlus speaker model", "Seed-VC CAMPPlus 話者モデル"],
        ["Seed-VC RMVPE 音高模型"] = ["Seed-VC RMVPE 音高模型", "Seed-VC RMVPE 音高模型", "Seed-VC RMVPE pitch model", "Seed-VC RMVPE 音程モデル"],
        ["Seed-VC BigVGAN 声码器"] = ["Seed-VC BigVGAN 声码器", "Seed-VC BigVGAN 聲碼器", "Seed-VC BigVGAN vocoder", "Seed-VC BigVGAN ボコーダー"],
        ["Seed-VC Whisper 编码器"] = ["Seed-VC Whisper 编码器", "Seed-VC Whisper 編碼器", "Seed-VC Whisper encoder", "Seed-VC Whisper エンコーダー"],
        ["隔离运行环境"] = ["隔离运行环境", "獨立執行環境", "isolated runtime", "専用ランタイム"],
        ["独立模型下载组件"] = ["独立模型下载组件", "獨立模型下載元件", "isolated model downloader", "専用モデルダウンローダー"],
        ["Qwen3-TTS Python 3.12 隔离环境"] = ["Qwen3-TTS Python 3.12 隔离环境", "Qwen3-TTS Python 3.12 獨立環境", "isolated Qwen3-TTS Python 3.12 environment", "Qwen3-TTS 専用 Python 3.12 環境"],
        ["Qwen3-TTS 所需的 SoX 音频组件"] = ["Qwen3-TTS 所需的 SoX 音频组件", "Qwen3-TTS 所需的 SoX 音訊元件", "SoX audio tools for Qwen3-TTS", "Qwen3-TTS 用 SoX 音声ツール"],
        ["FFmpeg 音频组件"] = ["FFmpeg 音频组件", "FFmpeg 音訊元件", "FFmpeg audio tools", "FFmpeg 音声ツール"],
        ["模型部署组件 uv"] = ["模型部署组件 uv", "模型部署元件 uv", "uv runtime installer", "uv ランタイムインストーラー"],
        ["BS-RoFormer-SW 多轨权重"] = ["BS-RoFormer-SW 多轨权重", "BS-RoFormer-SW 多軌權重", "BS-RoFormer-SW multistem weights", "BS-RoFormer-SW マルチステムモデル"],
        ["YourMT3+ 多乐器权重"] = ["YourMT3+ 多乐器权重", "YourMT3+ 多樂器權重", "YourMT3+ multi-instrument weights", "YourMT3+ 多楽器モデル"],
        ["正在校验官方模型文件"] = ["正在校验官方模型文件", "正在驗證官方模型檔案", "Verifying official model files", "公式モデルファイルを検証中"],
        ["正在校验 GitHub Release 摘要"] = ["正在校验 GitHub Release 摘要", "正在驗證 GitHub Release 摘要", "Verifying the GitHub Release digest", "GitHub Release のダイジェストを検証中"],
        ["正在检查模型部署组件"] = ["正在检查模型部署组件", "正在檢查模型部署元件", "Checking model installation tools", "モデル導入ツールを確認中"],
        ["正在校验模型包完整性"] = ["正在校验模型包完整性", "正在驗證模型套件完整性", "Verifying model package integrity", "モデルパッケージの整合性を検証中"],
        ["正在安装模型文件"] = ["正在安装模型文件", "正在安裝模型檔案", "Installing model files", "モデルファイルをインストール中"],
        ["正在读取模型版本"] = ["正在读取模型版本", "正在讀取模型版本", "Reading model version", "モデルのバージョンを確認中"],
        ["分轨模式"] = ["分轨模式", "分軌模式", "Stem mode", "ステムモード"],
        ["二轨：人声 + 伴奏"] = ["二轨：人声 + 伴奏", "二軌：人聲 + 伴奏", "Two stems: vocals + instrumental", "2 ステム：ボーカル + 伴奏"],
        ["多轨：完整分轨"] = ["多轨：完整分轨", "多軌：完整分軌", "Multi-stem: full separation", "マルチステム：完全分離"],
        ["今天想创作什么？"] = ["今天想创作什么？", "今天想創作什麼？", "What would you like to create?", "今日は何を作りますか？"],
        ["六个功能互相独立，不需要先新建项目。选择功能后，再按提示添加素材、模型和输出位置。"] = ["六个功能互相独立，不需要先新建项目。选择功能后，再按提示添加素材、模型和输出位置。", "六個功能彼此獨立，不需要先建立專案。選擇功能後，再依提示加入素材、模型和輸出位置。", "All six features work independently—no project setup required. Choose a feature, then follow the prompts for media, models, and output location.", "6つの機能はそれぞれ独立しており、プロジェクト作成は不要です。機能を選び、素材、モデル、出力先の案内に従ってください。"],
        ["创作音乐"] = ["创作音乐", "創作音樂", "Create music", "音楽を作る"],
        ["制作配音"] = ["制作配音", "製作配音", "Create a voice", "音声を作る"],
        ["克隆歌声"] = ["克隆歌声", "克隆歌聲", "Clone singing voice", "歌声をクローン"],
        ["转换与克隆演唱音色"] = ["转换与克隆演唱音色", "轉換與克隆演唱音色", "Convert and clone singing voices", "歌声の変換とクローン"],
        ["拆分混音"] = ["拆分混音", "拆分混音", "Split a mix", "ミックスを分離"],
        ["音频转 MIDI"] = ["音频转 MIDI", "音訊轉 MIDI", "Audio to MIDI", "音声を MIDI へ"],
        ["生成字幕"] = ["生成字幕", "產生字幕", "Generate subtitles", "字幕を生成"],
        ["第一次使用？直接选择功能"] = ["第一次使用？直接选择功能", "第一次使用？直接選擇功能", "New here? Choose a feature", "初めてですか？機能を選びましょう"],
        ["不需要新建项目。进入任一功能后，Aurora 会根据当前任务提示所需的素材、模型和输出位置。"] = ["不需要新建项目。进入任一功能后，Aurora 会根据当前任务提示所需的素材、模型和输出位置。", "不需要建立專案。進入任一功能後，Aurora 會依目前任務提示所需的素材、模型和輸出位置。", "No project setup is required. Open any feature and Aurora will prompt for the media, model, and output location needed for that task.", "プロジェクト作成は不要です。機能を開くと、タスクに必要な素材、モデル、出力先が案内されます。"],
        ["最近处理记录"] = ["最近处理记录", "最近處理記錄", "Recent processing records", "最近の処理履歴"],
        ["再次处理"] = ["再次处理", "再次處理", "Run again", "再処理"],
        ["完成分轨、扒谱或字幕任务后，处理记录会出现在这里。"] = ["完成分轨、扒谱或字幕任务后，处理记录会出现在这里。", "完成分軌、扒譜或字幕任務後，處理記錄會顯示在這裡。", "Processing records appear here after separation, transcription, or subtitle tasks finish.", "分離、採譜、字幕タスクの完了後、処理履歴がここに表示されます。"],
        ["正在进行"] = ["正在进行", "進行中", "In progress", "進行中"],
        ["查看全部任务"] = ["查看全部任务", "查看全部任務", "View all tasks", "すべてのタスク"],
        ["所有本地任务"] = ["所有本地任务", "所有本機任務", "All local tasks", "すべてのローカルタスク"],
        ["继续"] = ["继续", "繼續", "Continue", "続ける"],
        ["打开"] = ["打开", "開啟", "Open", "開く"],
        ["重试"] = ["重试", "重試", "Retry", "再試行"],
        ["取消"] = ["取消", "取消", "Cancel", "キャンセル"],
        ["检查全部更新"] = ["检查全部更新", "檢查全部更新", "Check all updates", "すべて更新確認"],
        ["更新全部"] = ["更新全部", "全部更新", "Update all", "すべて更新"],
        ["有更新"] = ["有更新", "有更新", "Update available", "更新あり"],
        ["更新"] = ["更新", "更新", "Update", "更新"],
        ["安装"] = ["安装", "安裝", "Install", "インストール"],
        ["稍后"] = ["稍后", "稍後", "Later", "後で"],
        ["将按顺序更新所有已发现的新版本，并保留可回退版本。是否继续？"] = ["将按顺序更新所有已发现的新版本，并保留可回退版本。是否继续？", "將依序更新所有已發現的新版本，並保留可回復版本。是否繼續？", "Aurora will update every detected component in sequence and keep rollback copies. Continue?", "検出したすべてのコンポーネントを順番に更新し、ロールバック用のコピーを保持します。続行しますか？"],
        ["组件正在使用"] = ["组件正在使用", "元件正在使用", "Component in use", "コンポーネントを使用中"],
        ["请先保存并关闭 {0}，然后重新点击更新。Aurora 不会强制关闭它，以免丢失未保存内容。"] = ["请先保存并关闭 {0}，然后重新点击更新。Aurora 不会强制关闭它，以免丢失未保存内容。", "請先儲存並關閉 {0}，再重新點擊更新。Aurora 不會強制關閉它，以免遺失未儲存內容。", "Save your work and close {0}, then select Update again. Aurora will not force-close it, so unsaved work is protected.", "作業を保存して {0} を終了し、もう一度更新してください。未保存の内容を守るため、Aurora は強制終了しません。"],
        ["以下组件仍在运行，请先保存并关闭后再更新：\n{0}"] = ["以下组件仍在运行，请先保存并关闭后再更新：\n{0}", "以下元件仍在執行中，請先儲存並關閉後再更新：\n{0}", "These components are still running. Save your work and close them before updating:\n{0}", "次のコンポーネントが実行中です。作業を保存して終了してから更新してください：\n{0}"],
        ["知道了"] = ["知道了", "知道了", "Got it", "了解"],
        ["查看本地文件"] = ["查看本地文件", "查看本機檔案", "View local files", "ローカルファイル"],
        ["检查 / 修复"] = ["检查 / 修复", "檢查 / 修復", "Check / Repair", "確認 / 修復"],
        ["回退"] = ["回退", "回復", "Roll back", "ロールバック"],
        ["卸载"] = ["卸载", "解除安裝", "Uninstall", "アンインストール"],
        ["重新扫描"] = ["重新扫描", "重新掃描", "Scan again", "再スキャン"],
        ["导出诊断包"] = ["导出诊断包", "匯出診斷套件", "Export diagnostics", "診断を出力"],
        ["打开日志"] = ["打开日志", "開啟日誌", "Open logs", "ログを開く"],
        ["运行环境"] = ["运行环境", "執行環境", "Runtime environment", "実行環境"],
        ["安全模式"] = ["安全模式", "安全模式", "Safe mode", "セーフモード"],
        ["任务完成后释放显存"] = ["任务完成后释放显存", "任務完成後釋放顯示記憶體", "Release VRAM after tasks", "完了後に VRAM を解放"],
        ["外观与语言"] = ["外观与语言", "外觀與語言", "Appearance and language", "表示と言語"],
        ["浅色"] = ["浅色", "淺色", "Light", "ライト"],
        ["深色"] = ["深色", "深色", "Dark", "ダーク"],
        ["跟随系统"] = ["跟随系统", "跟隨系統", "Use system setting", "システム設定を使用"],
        ["界面语言"] = ["界面语言", "介面語言", "Interface language", "表示言語"],
        ["主题"] = ["主题", "主題", "Theme", "テーマ"],
        ["模型目录"] = ["模型目录", "模型目錄", "Model folder", "モデルフォルダー"],
        ["成品目录"] = ["成品目录", "成品目錄", "Output folder", "出力フォルダー"],
        ["处理记录目录"] = ["处理记录目录", "處理記錄目錄", "Processing records folder", "処理履歴フォルダー"],
        ["保存设置"] = ["保存设置", "儲存設定", "Save settings", "設定を保存"],
        ["设置已保存。"] = ["设置已保存。", "設定已儲存。", "Settings saved.", "設定を保存しました。"],
        ["每天首次启动时检查应用更新"] = ["每天首次启动时检查应用更新", "每天首次啟動時檢查應用程式更新", "Check app updates on the first launch each day", "毎日の初回起動時にアプリ更新を確認"],
        ["启动时检查模型更新"] = ["启动时检查模型更新", "啟動時檢查模型更新", "Check model updates at startup", "起動時にモデル更新を確認"],
        ["下载大型模型前始终确认"] = ["下载大型模型前始终确认", "下載大型模型前一律確認", "Confirm large model downloads", "大容量モデルの前に確認"],
        ["任务完成后自动释放显存"] = ["任务完成后自动释放显存", "任務完成後自動釋放顯示記憶體", "Release VRAM automatically", "VRAM を自動解放"],
        ["进入工作台"] = ["进入工作台", "進入工作台", "Open workbench", "ワークベンチを開く"],
        ["查看我的成品"] = ["查看我的成品", "查看我的成品", "View my creations", "作品を見る"],
        ["开始处理"] = ["开始处理", "開始處理", "Start processing", "処理を開始"],
        ["选择文件"] = ["选择文件", "選擇檔案", "Choose file", "ファイルを選択"],
        ["打开成品目录"] = ["打开成品目录", "開啟成品目錄", "Open output folder", "出力フォルダー"],
        ["检查更新"] = ["检查更新", "檢查更新", "Check for updates", "更新を確認"],
        ["导出诊断"] = ["导出诊断", "匯出診斷", "Export diagnostics", "診断を出力"],
        ["我的成品"] = ["我的成品", "我的成品", "My creations", "マイ作品"],
        ["结束当前引擎"] = ["结束当前引擎", "結束目前引擎", "Stop current engine", "現在のエンジンを終了"],
        ["创作引擎与模型"] = ["创作引擎与模型", "創作引擎與模型", "Creative engines and models", "制作エンジンとモデル"],
        ["正在读取本地模型…"] = ["正在读取本地模型…", "正在讀取本機模型…", "Reading local models…", "ローカルモデルを確認しています…"],
        ["全部模型"] = ["全部模型", "全部模型", "All models", "すべてのモデル"],
        ["已安装"] = ["已安装", "已安裝", "Installed", "インストール済み"],
        ["默认组件"] = ["默认组件", "預設元件", "Default components", "標準コンポーネント"],
        ["可选模型"] = ["可选模型", "選用模型", "Optional models", "オプションモデル"],
        ["0.9.8 · 完整汉化更新提示，扩展模型中心信息，并新增三档 Faster-Whisper 多语言字幕模型。"] = [
            "0.9.8 · 完整汉化更新提示，扩展模型中心信息，并新增三档 Faster-Whisper 多语言字幕模型。",
            "0.9.8 · 完整在地化更新提示、擴充模型中心資訊，並新增三種 Faster-Whisper 多語言字幕模型。",
            "0.9.8 · Localized update results, richer Model Center details, and three additional multilingual Faster-Whisper models.",
            "0.9.8 · 更新結果の完全なローカライズ、モデルセンターの情報拡充、3 種類の多言語 Faster-Whisper モデルを追加。"],
        ["0.9.8 · 本地 AI 音频创作工作台"] = ["0.9.8 · 本地 AI 音频创作工作台", "0.9.8 · 本機 AI 音訊創作工作台", "0.9.8 · Local AI audio production workbench", "0.9.8 · ローカル AI オーディオ制作ワークベンチ"],
        ["为音乐、声音与影像创作者打造的一站式本地工作台。灵感、素材与成品，始终由你掌控。"] = ["为音乐、声音与影像创作者打造的一站式本地工作台。灵感、素材与成品，始终由你掌控。", "為音樂、聲音與影像創作者打造的一站式本機工作台。靈感、素材與成品，始終由你掌控。", "A unified local workbench for music, voice, and video creators. Your ideas, source files, and finished work remain under your control.", "音楽・音声・映像クリエイターのための統合ローカルワークベンチ。アイデア、素材、完成作品は常に自分で管理できます。"],
        ["更新日志"] = ["更新日志", "更新記錄", "Release notes", "更新履歴"],
        ["Copyright © 2026 Aurora Contributors. Licensed under GNU GPL v3.0."] = ["版权所有 © 2026 Aurora Contributors。采用 GNU GPL v3.0 许可。", "版權所有 © 2026 Aurora Contributors。採用 GNU GPL v3.0 授權。", "Copyright © 2026 Aurora Contributors. Licensed under GNU GPL v3.0.", "Copyright © 2026 Aurora Contributors。GNU GPL v3.0 に基づき提供。"],
        ["0.9.7 · 模型选择更完整：新增轻量配音、声音克隆、通用分轨与轻量扒谱引擎，均由用户按需安装。"] = [
            "0.9.7 · 模型选择更完整：新增轻量配音、声音克隆、通用分轨与轻量扒谱引擎，均由用户按需安装。",
            "0.9.7 · 模型選擇更完整：新增輕量配音、聲音複製、通用分軌與輕量扒譜引擎，均由使用者按需安裝。",
            "0.9.7 · More model choices: lightweight speech, voice cloning, general-purpose stems, and MIDI engines are now available on demand.",
            "0.9.7 · モデル選択を拡充：軽量音声、ボイスクローン、汎用音源分離、MIDI エンジンを必要に応じて導入できます。"],
        ["等待本地引擎"] = ["等待本地引擎", "等待本機引擎", "Waiting for local engine", "ローカルエンジンを待機中"],
        ["队列已暂停"] = ["队列已暂停", "佇列已暫停", "Queue paused", "キュー一時停止中"],
        ["正在准备模型与工作区"] = ["正在准备模型与工作区", "正在準備模型與工作區", "Preparing model and workspace", "モデルと作業領域を準備中"],
        ["正在本机处理"] = ["正在本机处理", "正在本機處理", "Processing locally", "ローカルで処理中"],
        ["处理完成"] = ["处理完成", "處理完成", "Processing complete", "処理完了"],
        ["需要处理"] = ["需要处理", "需要處理", "Needs attention", "確認が必要"],
        ["已安全取消"] = ["已安全取消", "已安全取消", "Canceled safely", "安全にキャンセル済み"],
        ["任务已取消。"] = ["任务已取消。", "任務已取消。", "The task was canceled.", "タスクをキャンセルしました。"],
        ["Recovered after restart"] = ["重启后可恢复", "重新啟動後可復原", "Recoverable after restart", "再起動後に復旧可能"],
        ["Aurora closed before this task finished. You can retry it."] = ["Aurora 在任务完成前关闭，可以重新运行此任务。", "Aurora 在任務完成前關閉，可以重新執行此任務。", "Aurora closed before this task finished. You can retry it.", "タスク完了前に Aurora が終了しました。再実行できます。"],
        ["当前没有排队任务"] = ["当前没有排队任务", "目前沒有排隊任務", "No tasks are queued", "待機中のタスクはありません"],
        ["暂停队列"] = ["暂停队列", "暫停佇列", "Pause queue", "キューを一時停止"],
        ["继续队列"] = ["继续队列", "繼續佇列", "Resume queue", "キューを再開"],
        ["从灵感到成品，一站完成生成、编辑与导出。"] = ["从灵感到成品，一站完成生成、编辑与导出。", "從靈感到成品，一站完成產生、編輯與匯出。", "Create, edit, and export from one local workspace.", "着想から完成まで、生成・編集・書き出しを一つの画面で行えます。"],
        ["开启你的下一次创作"] = ["开启你的下一次创作", "開啟你的下一次創作", "Start your next creation", "次の制作を始めましょう"],
        ["选择创作引擎，即刻在 Aurora 中开始。所有处理均在本机完成。"] = ["选择创作引擎，即刻在 Aurora 中开始。所有处理均在本机完成。", "選擇創作引擎，即刻在 Aurora 中開始。所有處理均在本機完成。", "Choose an engine to begin. All processing stays on this PC.", "エンジンを選んで開始します。すべての処理はこの PC 内で行われます。"],
        ["正在启动本地引擎，首次加载可能需要几分钟…"] = ["正在启动本地引擎，首次加载可能需要几分钟…", "正在啟動本機引擎，首次載入可能需要幾分鐘…", "Starting the local engine. The first load may take a few minutes…", "ローカルエンジンを起動中です。初回は数分かかる場合があります…"],
        ["取消启动"] = ["取消启动", "取消啟動", "Cancel startup", "起動をキャンセル"],
        ["创作引擎选择"] = ["创作引擎选择", "創作引擎選擇", "Creative engine selector", "制作エンジン選択"],
        ["处理引擎选择"] = ["处理引擎选择", "處理引擎選擇", "Processing engine selector", "処理エンジン選択"],
        ["模型筛选"] = ["模型筛选", "模型篩選", "Model filter", "モデルフィルター"],
        ["暂时无法进入工作台"] = ["暂时无法进入工作台", "暫時無法進入工作台", "Workbench could not start", "ワークベンチを起動できません"],
        ["请按下方提示检查模型，修复后再试。"] = ["请按下方提示检查模型，修复后再试。", "請依下方提示檢查模型，修復後再試。", "Follow the message below, repair the model, and try again.", "下の案内に従ってモデルを修復し、もう一度お試しください。"],
        ["创作引擎启动已取消。"] = ["创作引擎启动已取消。", "創作引擎啟動已取消。", "Engine startup was canceled.", "エンジンの起動をキャンセルしました。"],
        ["从混音中分离人声、鼓、贝斯等独立音轨。"] = ["从混音中分离人声、鼓、贝斯等独立音轨。", "從混音中分離人聲、鼓、貝斯等獨立音軌。", "Separate vocals, drums, bass, and other stems from a mix.", "ミックスからボーカル、ドラム、ベースなどを分離します。"],
        ["将演奏音频转换为可继续编辑的 MIDI 乐谱。"] = ["将演奏音频转换为可继续编辑的 MIDI 乐谱。", "將演奏音訊轉換為可繼續編輯的 MIDI 樂譜。", "Convert performed audio into editable MIDI.", "演奏音声を編集可能な MIDI に変換します。"],
        ["从视频中识别语音，生成带时间轴的字幕文件。"] = ["从视频中识别语音，生成带时间轴的字幕文件。", "從影片中辨識語音，產生帶時間軸的字幕檔。", "Recognize speech in video and create timed subtitles.", "動画の音声を認識してタイムコード付き字幕を作成します。"],
        ["新建分轨任务"] = ["新建分轨任务", "新增分軌任務", "New separation task", "新しい音源分離タスク"],
        ["新建扒谱任务"] = ["新建扒谱任务", "新增扒譜任務", "New MIDI transcription task", "新しい MIDI 採譜タスク"],
        ["新建字幕任务"] = ["新建字幕任务", "新增字幕任務", "New subtitle task", "新しい字幕タスク"],
        ["新建处理任务"] = ["新建处理任务", "新增處理任務", "New processing task", "新しい処理タスク"],
        ["选择音频或视频素材，Aurora 会在本机生成六轨分离结果。"] = ["选择音频或视频素材，Aurora 会在本机生成六轨分离结果。", "選擇音訊或影片素材，Aurora 會在本機產生六軌分離結果。", "Choose audio or video and Aurora will create separated stems locally.", "音声または動画を選ぶと、Aurora がローカルでステムを分離します。"],
        ["选择演奏录音并匹配识别引擎，生成可继续编曲的 MIDI 文件。"] = ["选择演奏录音并匹配识别引擎，生成可继续编曲的 MIDI 文件。", "選擇演奏錄音並配對辨識引擎，產生可繼續編曲的 MIDI 檔。", "Choose a performance and engine to create editable MIDI.", "演奏録音とエンジンを選び、編集可能な MIDI を作成します。"],
        ["选择视频素材，Aurora 会在本机完成语音识别与字幕生成。"] = ["选择视频素材，Aurora 会在本机完成语音识别与字幕生成。", "選擇影片素材，Aurora 會在本機完成語音辨識與字幕產生。", "Choose a video; speech recognition and subtitles run locally.", "動画を選ぶと、音声認識と字幕生成をローカルで実行します。"],
        ["支持 WAV、FLAC、MP3、M4A、MP4 等常见格式"] = ["支持 WAV、FLAC、MP3、M4A、MP4 等常见格式", "支援 WAV、FLAC、MP3、M4A、MP4 等常見格式", "Supports WAV, FLAC, MP3, M4A, MP4, and other common formats", "WAV、FLAC、MP3、M4A、MP4 などに対応"],
        ["建议使用人声较少、乐器清晰的音频素材"] = ["建议使用人声较少、乐器清晰的音频素材", "建議使用人聲較少、樂器清晰的音訊素材", "Use clear instrumental audio with minimal vocals for best results", "ボーカルが少なく楽器が明瞭な音源を推奨"],
        ["支持常见视频格式，清晰人声能获得更好的识别效果"] = ["支持常见视频格式，清晰人声能获得更好的识别效果", "支援常見影片格式，清晰人聲能獲得更好的辨識效果", "Supports common video formats; clear speech improves accuracy", "一般的な動画形式に対応。明瞭な音声ほど精度が上がります"],
        ["输出为可继续混音的独立 WAV 音轨。"] = ["输出为可继续混音的独立 WAV 音轨。", "輸出為可繼續混音的獨立 WAV 音軌。", "Outputs separate WAV stems ready for mixing.", "ミックスに使える個別 WAV ステムを出力します。"],
        ["处理结果会保存为标准 MIDI 文件。"] = ["处理结果会保存为标准 MIDI 文件。", "處理結果會儲存為標準 MIDI 檔。", "The result is saved as a standard MIDI file.", "結果は標準 MIDI ファイルとして保存されます。"],
        ["处理结果会保存到视频字幕成品目录。"] = ["处理结果会保存到视频字幕成品目录。", "處理結果會儲存到影片字幕成品目錄。", "Results are saved in the video subtitle output folder.", "結果は動画字幕の出力フォルダーに保存されます。"],
        ["源文件与批处理"] = ["源文件与批处理", "來源檔案與批次處理", "Source files and batch", "素材と一括処理"],
        ["添加素材"] = ["添加素材", "加入素材", "Add media", "素材を追加"],
        ["清空"] = ["清空", "清空", "Clear", "クリア"],
        ["选择素材后可在此预览"] = ["选择素材后可在此预览", "選擇素材後可在此預覽", "Select media to preview it here", "素材を選ぶとここでプレビューできます"],
        ["处理引擎"] = ["处理引擎", "處理引擎", "Processing engine", "処理エンジン"],
        ["处理预设"] = ["处理预设", "處理預設", "Processing preset", "処理プリセット"],
        ["快速草稿"] = ["快速草稿", "快速草稿", "Fast draft", "高速ドラフト"],
        ["推荐质量"] = ["推荐质量", "建議品質", "Recommended quality", "推奨品質"],
        ["高质量"] = ["高质量", "高品質", "High quality", "高品質"],
        ["任务动态"] = ["任务动态", "任務動態", "Task activity", "タスクの動き"],
        ["当前会话的状态与处理记录"] = ["当前会话的状态与处理记录", "目前工作階段的狀態與處理記錄", "Status and activity for this session", "現在のセッションの状態と履歴"],
        ["当前状态"] = ["当前状态", "目前狀態", "Current status", "現在の状態"],
        ["输出位置"] = ["输出位置", "輸出位置", "Output location", "出力先"],
        ["活动记录"] = ["活动记录", "活動記錄", "Activity log", "アクティビティ"],
        ["清空记录"] = ["清空记录", "清空記錄", "Clear log", "履歴を消去"],
        ["在 Aurora 中完成"] = ["在 Aurora 中完成", "在 Aurora 中完成", "Keep it in Aurora", "Aurora 内で完結"],
        ["素材、处理过程与结果路径都留在同一个工作区；关闭应用时，Aurora 会安全结束由它启动的任务。"] = ["素材、处理过程与结果路径都留在同一个工作区；关闭应用时，Aurora 会安全结束由它启动的任务。", "素材、處理過程與結果路徑都留在同一個工作區；關閉應用程式時，Aurora 會安全結束由它啟動的任務。", "Media, processing, and results stay in one workspace. Aurora safely stops tasks it started when the app closes.", "素材、処理、結果は一つの作業領域に保存され、終了時は Aurora が起動したタスクを安全に停止します。"],
        ["请先添加受支持的素材。"] = ["请先添加受支持的素材。", "請先加入支援的素材。", "Add supported media first.", "対応する素材を先に追加してください。"],
        ["请先在模型管理中安装或修复所选引擎。"] = ["请先在模型管理中安装或修复所选引擎。", "請先在模型管理中安裝或修復所選引擎。", "Install or repair the selected engine in Model Center first.", "モデルセンターで選択したエンジンをインストールまたは修復してください。"],
        ["请先关闭安全模式。"] = ["请先关闭安全模式。", "請先關閉安全模式。", "Turn off Safe mode first.", "セーフモードを先にオフにしてください。"],
        ["开始本地处理。"] = ["开始本地处理。", "開始本機處理。", "Start local processing.", "ローカル処理を開始します。"],
        ["浏览…"] = ["浏览…", "瀏覽…", "Browse…", "参照…"],
        ["允许启动通过检查的引擎"] = ["允许启动通过检查的引擎", "允許啟動通過檢查的引擎", "Allow verified engines to start", "確認済みエンジンの起動を許可"],
        ["仅查看任务与诊断"] = ["仅查看任务与诊断", "僅查看任務與診斷", "Tasks and diagnostics only", "タスクと診断のみ"],
        ["安全模式不会删除或更改模型，只会阻止第三方引擎启动，适合排查启动问题。"] = ["安全模式不会删除或更改模型，只会阻止第三方引擎启动，适合排查启动问题。", "安全模式不會刪除或變更模型，只會阻止第三方引擎啟動，適合排查啟動問題。", "Safe mode does not change models; it only blocks third-party engines while troubleshooting startup.", "セーフモードはモデルを変更せず、起動診断中に外部エンジンだけを停止します。"],
        ["查看更新日志"] = ["查看更新日志", "查看更新記錄", "View release notes", "更新履歴を表示"],
        ["反馈问题或建议"] = ["反馈问题或建议", "回報問題或建議", "Send feedback or suggestions", "問題や提案を送る"],
        ["反馈问题 / 建议"] = ["反馈问题 / 建议", "回報問題 / 建議", "Feedback / Suggestions", "フィードバック / 提案"],
        ["等待"] = ["等待", "等待", "Waiting", "待機中"],
        ["文字到完整歌曲"] = ["文字到完整歌曲", "文字到完整歌曲", "Text to music", "テキストから楽曲へ"],
        ["设计与克隆音色"] = ["设计与克隆音色", "設計與複製音色", "Design and clone voices", "声のデザインとクローン"],
        ["人声与乐器分轨"] = ["人声与乐器分轨", "人聲與樂器分軌", "Separate vocals and instruments", "ボーカルと楽器を分離"],
        ["识别演奏与旋律"] = ["识别演奏与旋律", "辨識演奏與旋律", "Transcribe piano performances", "ピアノ演奏を採譜"],
        ["视频语音到时间轴"] = ["视频语音到时间轴", "影片語音到時間軸", "Speech to timed captions", "動画音声から字幕へ"],
        ["创作引擎"] = ["创作引擎", "創作引擎", "Creative engine", "制作エンジン"],
        ["保存位置"] = ["保存位置", "儲存位置", "Save location", "保存先"],
        ["运行状态"] = ["运行状态", "執行狀態", "Runtime status", "実行状態"],
        ["中文"] = ["中文", "中文", "Chinese", "中国語"],
        ["队列会按顺序使用 GPU；重启 Aurora 后仍可查看、重试或打开结果。"] = ["队列会按顺序执行；重启后可重新执行保留的任务。", "佇列會依序執行；重新啟動後可重新執行保留的任務。", "Tasks run sequentially. Retained tasks can be restarted after reopening Aurora.", "順番にタスクを実行します。再起動後も保持したタスクを再実行できます。"],
        ["日志"] = ["日志", "記錄", "Log", "ログ"],
        ["任务日志"] = ["任务日志", "任務記錄", "Task log", "タスクログ"],
        ["还没有任务记录"] = ["还没有任务记录", "還沒有任務記錄", "No tasks yet", "タスクはまだありません"],
        ["从首页选择一个创作任务，Aurora 会在这里保留进度与结果。"] = ["从首页选择一个创作任务，Aurora 会在这里保留进度与结果。", "從首頁選擇創作任務，Aurora 會在這裡保留進度與成果。", "Choose a workflow from Home. Aurora keeps its progress and results here.", "ホームから機能を選択すると、進捗と成果がここに表示されます。"],
        ["按时间查看 Aurora 生成的音轨、MIDI、字幕与其他成品。"] = ["按时间查看 Aurora 生成的音轨、MIDI、字幕与其他成品。", "依時間查看 Aurora 產生的音軌、MIDI、字幕與其他成品。", "Browse generated audio, MIDI, and subtitles by date.", "音声、MIDI、字幕などの成果を日時順に確認します。"],
        ["还没有成品"] = ["还没有成品", "還沒有成品", "No results yet", "成果はまだありません"],
        ["完成任务后，结果会自动汇总到这里。"] = ["完成任务后，结果会自动汇总到这里。", "完成任務後，成果會自動彙整到這裡。", "Completed output is added here automatically.", "完了した成果はここに自動で追加されます。"],
        ["安装详情"] = ["安装详情", "安裝詳情", "Installation details", "インストールの詳細"],
        ["素材语言"] = ["素材语言", "素材語言", "Source language", "素材の言語"],
        ["声音克隆"] = ["声音克隆", "聲音複製", "Voice cloning", "声のクローン"],
        ["专业音色"] = ["专业音色", "專業音色", "Preset voices", "プリセット音声"],
        ["音色设计"] = ["音色设计", "音色設計", "Voice design", "声のデザイン"],
        ["轻量声音克隆"] = ["轻量声音克隆", "輕量聲音複製", "Lightweight cloning", "軽量な声のクローン"],
        ["轻量专业音色"] = ["轻量专业音色", "輕量專業音色", "Lightweight preset voices", "軽量プリセット音声"],
        ["多语言声音克隆"] = ["多语言声音克隆", "多語言聲音複製", "Multilingual cloning", "多言語の声のクローン"],
        ["可控配音"] = ["可控配音", "可控配音", "Controllable voice", "制御可能な音声"],
        ["零样本歌声转换"] = ["零样本歌声转换", "零樣本歌聲轉換", "Zero-shot singing conversion", "ゼロショット歌声変換"],
        ["多轨高质量"] = ["多轨高质量", "多軌高品質", "High-quality multistem", "高品質マルチステム"],
        ["二轨"] = ["二轨", "二軌", "Two stems", "2 ステム"],
        ["通用四轨分离"] = ["通用四轨分离", "通用四軌分離", "General four-stem separation", "汎用 4 ステム分離"],
        ["钢琴扒谱"] = ["钢琴扒谱", "鋼琴扒譜", "Piano transcription", "ピアノ採譜"],
        ["经典模型"] = ["经典模型", "經典模型", "Classic model", "従来モデル"],
        ["轻量扒谱"] = ["轻量扒谱", "輕量扒譜", "Lightweight transcription", "軽量採譜"],
        ["快速识别"] = ["快速识别", "快速辨識", "Fast recognition", "高速認識"],
        ["高质量识别"] = ["高质量识别", "高品質辨識", "High-quality recognition", "高品質認識"],
        ["词级时间轴"] = ["词级时间轴", "詞級時間軸", "Word-level alignment", "単語単位の時刻合わせ"],
        ["Task completed."] = ["任务已完成。", "任務已完成。", "Task completed.", "タスクが完了しました。"],
        ["AI 分轨"] = ["AI 分轨", "AI 分軌", "Stem separation", "音源分離"],
        ["AI 扒谱"] = ["AI 扒谱", "AI 扒譜", "MIDI transcription", "MIDI 採譜"],
        ["视频字幕"] = ["视频字幕", "影片字幕", "Video subtitles", "動画字幕"],
        ["字幕"] = ["字幕", "字幕", "Subtitles", "字幕"],
        ["配音"] = ["配音", "配音", "Voice", "音声"],
        ["歌声"] = ["歌声", "歌聲", "Singing", "歌声"],
        ["音乐"] = ["音乐", "音樂", "Music", "音楽"],
        ["等待添加素材"] = ["等待添加素材", "等待加入素材", "Add media to begin", "素材を追加してください"],
        ["正在等待安装进程返回最新活动…"] = ["正在等待安装进程返回最新活动…", "正在等待安裝程序回傳最新活動…", "Waiting for the installer to report progress…", "インストーラーの進捗を待っています…"],
        ["正在安全停止当前操作…"] = ["正在安全停止当前操作…", "正在安全停止目前操作…", "Stopping the current operation safely…", "現在の操作を安全に停止しています…"],
        ["正在读取 GPU 信息…"] = ["正在读取 GPU 信息…", "正在讀取 GPU 資訊…", "Reading GPU information…", "GPU 情報を読み込み中…"],
        ["处理记录已载入，可以重新处理或查看原素材。"] = ["处理记录已载入，可以重新处理或查看原素材。", "處理記錄已載入，可以重新處理或查看原素材。", "Processing record loaded. Run again or inspect the source.", "処理履歴を読み込みました。再実行または素材を確認できます。"],
        ["自动识别"] = ["自动识别", "自動識別", "Auto detect", "自動判定"],
        ["预览"] = ["预览", "預覽", "Preview", "プレビュー"],
        ["导出"] = ["导出", "匯出", "Export", "書き出す"],
        ["复制路径"] = ["复制路径", "複製路徑", "Copy path", "パスをコピー"],
        ["打开位置"] = ["打开位置", "開啟位置", "Open folder", "フォルダーを開く"],
        ["取消本批任务"] = ["取消本批任务", "取消本批任務", "Cancel batch", "バッチを中止"],
        ["编辑字幕"] = ["编辑字幕", "編輯字幕", "Edit subtitles", "字幕を編集"],
        ["保存副本"] = ["保存副本", "儲存副本", "Save a copy", "コピーを保存"],
        ["用默认程序打开"] = ["用默认程序打开", "用預設程式開啟", "Open in default app", "既定のアプリで開く"],
        ["成品路径已复制。"] = ["成品路径已复制。", "成品路徑已複製。", "Result path copied.", "成果のパスをコピーしました。"],
        ["成品已自动加入成品库。"] = ["成品已自动加入成品库。", "成品已自動加入成品庫。", "Output added to Results.", "成果をライブラリに追加しました。"],
        ["任务已安全取消。"] = ["任务已安全取消。", "任務已安全取消。", "Task canceled safely.", "タスクを安全に中止しました。"],
        ["安全模式已启用，无法执行或重试任务。"] = ["安全模式已启用，无法执行或重试任务。", "安全模式已啟用，無法執行或重試任務。", "Safe mode blocks running and retrying tasks.", "セーフモードでは実行・再試行できません。"],
        ["请先结束运行中的任务与引擎，再更改保存目录。"] = ["请先结束运行中的任务与引擎，再更改保存目录。", "請先結束執行中的任務與引擎，再變更儲存目錄。", "Stop active tasks and engines before changing storage folders.", "保存先の変更前にタスクとエンジンを終了してください。"],
        ["请先安装可打开 MIDI 的音乐软件。"] = ["请先安装可打开 MIDI 的音乐软件。", "請先安裝可開啟 MIDI 的音樂軟體。", "Install a music app that opens MIDI files first.", "MIDI に対応する音楽ソフトをインストールしてください。"],
        ["字幕超过 2 MB，请使用外部编辑器打开。"] = ["字幕超过 2 MB，请使用外部编辑器打开。", "字幕超過 2 MB，請使用外部編輯器開啟。", "Subtitles exceed 2 MB. Use an external editor.", "字幕が 2 MB を超えています。外部エディターを使用してください。"],
        ["待恢复"] = ["待恢复", "待恢復", "Ready to retry", "再実行可能"],
        ["上次未完成的任务已保留，可继续处理或取消。"] = ["上次未完成的任务已保留，可继续处理或取消。", "上次未完成的任務已保留，可繼續處理或取消。", "The unfinished task was retained. Retry it or cancel.", "未完了タスクを保持しました。再実行または中止できます。"]
    };

    public string Get(string key)
    {
        if (!values.TryGetValue(key, out var options) && !phrases.TryGetValue(key, out options)) return key;
        return settings.EffectiveLanguage() switch
        {
            "zh-TW" => options[1],
            "en-US" => options[2],
            "ja-JP" => options[3],
            _ => options[0]
        };
    }

    public string Translate(string source)
    {
        if (string.IsNullOrEmpty(source)) return source;
        if (source.StartsWith("Starting ", StringComparison.Ordinal)) source = "正在启动 " + source[9..];
        if (values.ContainsKey(source) || phrases.ContainsKey(source)) return Get(source);
        var pair = phrases.Concat(values).FirstOrDefault(x => x.Value.Contains(source, StringComparer.OrdinalIgnoreCase));
        if (pair.Value is null)
        {
            foreach (var template in templates)
            {
                var pattern = "^" + System.Text.RegularExpressions.Regex.Escape(template[0]).Replace("\\{0}", "(.+?)").Replace("\\{1}", "(.+?)") + "$";
                var match = System.Text.RegularExpressions.Regex.Match(source, pattern, System.Text.RegularExpressions.RegexOptions.Singleline);
                if (!match.Success) continue;
                var index = settings.EffectiveLanguage() switch { "zh-TW" => 1, "en-US" => 2, "ja-JP" => 3, _ => 0 };
                var args = match.Groups.Cast<System.Text.RegularExpressions.Group>().Skip(1).Select(group => string.Join(" · ", group.Value.Split(" · ").Select(part => phrases.ContainsKey(part) || values.ContainsKey(part) ? Get(part) : part))).Cast<object>().ToArray();
                return string.Format(template[index], args);
            }
            return source;
        }
        return settings.EffectiveLanguage() switch { "zh-TW" => pair.Value[1], "en-US" => pair.Value[2], "ja-JP" => pair.Value[3], _ => pair.Value[0] };
    }

    private static readonly string[][] templates =
    [
        ["正在准备 {0}", "正在準備 {0}", "Preparing {0}", "{0} を準備中"],
        ["正在安装 {0}", "正在安裝 {0}", "Installing {0}", "{0} をインストール中"],
        ["正在部署 {0}", "正在部署 {0}", "Setting up {0}", "{0} を設定中"],
        ["正在下载 {0}", "正在下載 {0}", "Downloading {0}", "{0} をダウンロード中"],
        ["正在配置 {0}", "正在設定 {0}", "Configuring {0}", "{0} を設定中"],
        ["正在创建 {0}", "正在建立 {0}", "Creating {0}", "{0} を作成中"],
        ["正在从 Hugging Face 下载 {0}", "正在從 Hugging Face 下載 {0}", "Downloading {0} from Hugging Face", "Hugging Face から {0} をダウンロード中"],
        ["正在从 BS-RoFormer 官方注册表下载 {0}", "正在從 BS-RoFormer 官方登錄表下載 {0}", "Downloading {0} from the BS-RoFormer registry", "BS-RoFormer レジストリから {0} をダウンロード中"],
        ["模型安装未完成：{0}", "模型安裝未完成：{0}", "Model installation did not complete: {0}", "モデルのインストールが完了しませんでした：{0}"],
        ["已添加 {0} 个素材。可继续添加或直接开始处理。", "已加入 {0} 個素材。可繼續加入或開始處理。", "Added {0} files. Add more or start processing.", "{0} 件の素材を追加しました。追加を続けるか、処理を開始できます。"],
        ["已是最新日期版 {0}", "已是最新日期版 {0}", "Latest dated version: {0}", "最新の日付版：{0}"],
        ["发现日期版 {0}", "發現日期版 {0}", "Dated update available: {0}", "日付版の更新があります：{0}"],
        ["已是最新正式版 {0}", "已是最新正式版 {0}", "Latest stable release: {0}", "最新の正式版：{0}"],
        ["发现正式版 {0}", "發現正式版 {0}", "Stable release available: {0}", "正式版の更新があります：{0}"],
        ["已是最新版本 {0}", "已是最新版本 {0}", "Up to date: {0}", "最新です：{0}"],
        ["发现新版本 {0}", "發現新版本 {0}", "Update available: {0}", "更新があります：{0}"],
        ["正在载入 {0} 工作台…", "正在載入 {0} 工作台…", "Loading {0} workbench…", "{0} ワークベンチを読み込み中…"],
        ["已连接 {0}", "已連線 {0}", "Connected to {0}", "{0} に接続済み"],
        ["正在启动 {0}…", "正在啟動 {0}…", "Starting {0}…", "{0} を起動中…"],
        ["正在处理：{0}", "正在處理：{0}", "Processing: {0}", "処理中：{0}"],
        ["工作台界面加载失败：{0}", "工作台介面載入失敗：{0}", "Workbench loading failed: {0}", "ワークベンチの読み込みに失敗：{0}"],
        ["{0} 已下载并部署完成", "{0} 已下載並部署完成", "{0} installed and configured", "{0} をインストール・設定しました"],
        ["{0} 已安装并通过上游校验", "{0} 已安裝並通過上游驗證", "{0} installed and verified upstream", "{0} のインストールと検証が完了しました"],
        ["{0} 已安装并校验", "{0} 已安裝並驗證", "{0} installed and checked", "{0} のインストールと確認が完了しました"],
        ["{0} 已恢复到上一个运行环境。", "{0} 已回復至上一個執行環境。", "{0} restored to the previous runtime.", "{0} を以前の実行環境に戻しました。"],
        ["{0} 已恢复到上一个可用版本。", "{0} 已回復至上一個可用版本。", "{0} restored to the retained version.", "{0} を保持したバージョンに戻しました。"],
        ["请先结束 {0} 再回退模型。", "請先結束 {0} 再回復模型。", "Stop {0} before rolling back the model.", "モデルを戻す前に {0} を終了してください。"],
        ["当前可用空间：{0}", "目前可用空間：{0}", "Available disk space: {0}", "空き容量：{0}"],
        ["任务失败：{0}", "任務失敗：{0}", "Task failed: {0}", "タスクが失敗しました：{0}"]
    ];

    public string Format(string key, params object[] args) => string.Format(Get(key), args);

    public IReadOnlyCollection<string[]> Translations => phrases.Values.Concat(values.Values).ToArray();
}
